### PR TITLE
Акназаров Арслан, M3238

### PR DESCRIPTION
**Pull request by Arimionim**

### CODE REVIEW

**Comment by ubique** [comment]
Не собирается:

$ make
Scanning dependencies of target OS_kidshell
[ 50%] Building CXX object CMakeFiles/OS_kidshell.dir/main.cpp.o
/home/amnesia/git/ifmo/os-kidshell/main.cpp: In function ‘std::vector<std::__cxx11::basic_string<char> > parseCommand(const string&)’:
/home/amnesia/git/ifmo/os-kidshell/main.cpp:36:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
/home/amnesia/git/ifmo/os-kidshell/main.cpp: In function ‘char** getEnvs()’:
/home/amnesia/git/ifmo/os-kidshell/main.cpp:45:9: error: ‘strcpy’ was not declared in this scope
         strcpy(ans[pos], (it.first + "=" + it.second).c_str());
         ^~~~~~
/home/amnesia/git/ifmo/os-kidshell/main.cpp:45:9: note: ‘strcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
/home/amnesia/git/ifmo/os-kidshell/main.cpp:7:1:
+#include <cstring>
 
/home/amnesia/git/ifmo/os-kidshell/main.cpp:45:9:
         strcpy(ans[pos], (it.first + "=" + it.second).c_str());
         ^~~~~~
/home/amnesia/git/ifmo/os-kidshell/main.cpp:41:12: warning: address of local variable ‘ans’ returned [-Wreturn-local-addr]
     char * ans[envPars.size()];
            ^~~
/home/amnesia/git/ifmo/os-kidshell/main.cpp: In function ‘void execute(const string&)’:
/home/amnesia/git/ifmo/os-kidshell/main.cpp:55:9: error: ‘strcpy’ was not declared in this scope
         strcpy(argv[i], (parsedCommand[i]).c_str());
         ^~~~~~
/home/amnesia/git/ifmo/os-kidshell/main.cpp:55:9: note: ‘strcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
make[2]: *** [CMakeFiles/OS_kidshell.dir/build.make:63: CMakeFiles/OS_kidshell.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/OS_kidshell.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by ubique** [comment]
Плохой код:

$ make
Scanning dependencies of target OS_kidshell
[ 50%] Building CXX object CMakeFiles/OS_kidshell.dir/main.o
/home/amnesia/git/ifmo/os-kidshell/main.cpp: In function ‘char** getEnvs()’:
/home/amnesia/git/ifmo/os-kidshell/main.cpp:43:12: warning: address of local variable ‘ans’ returned [-Wreturn-local-addr]
     char * ans[envPars.size()];
            ^~~
[100%] Linking CXX executable OS_kidshell
[100%] Built target OS_kidshell

**Comment by ubique** [comment]
Некорректно обрабатывается Ctrl-D:

$ ./OS_kidshell 
:help for this message
:exit for exit
:set <name> <val> set par with <name> to <val>
:unset <name> for unset
:unsetall fot clear all env pars
*** stack smashing detected ***: <unknown> terminated

return code: 0
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)

**Comment by ubique** [comment]
Не работает:

$ ./OS_kidshell 
:help for this message
:exit for exit
:set <name> <val> set par with <name> to <val>
:unset <name> for unset
:unsetall fot clear all env pars
sdf

return code: 0
Segmentation fault (core dumped)

**Comment by Arimionim** [comment]
Никак не могу поймать segfault 
Можете, пожалуйста, скинуть код sdf

**Comment by ubique** [comment]
sdf - это просто какая-то случайная комбинация клавиш, программы с таким именем нет.

**Comment by ubique** [comment]
$ ./OS_kidshell 
:help for this message
:exit for exit
:set <name> <val> set par with <name> to <val>
:unset <name> for unset
:unsetall fot clear all env pars
/bin/ls
can't execute

return code: 0
Bus error (core dumped)

У вас осталась последняя попытка сдачи работы.

**Comment by Arimionim** [comment]
Это не было попыткой, я просто запушил декоративные изменения и не изменил описание коммита(11.05.2019, 19:16, "Dmitry Banschikov" <notifications@github.com>:$ ./OS_kidshell
:help for this message
:exit for exit
:set   set par with  to 
:unset  for unset
:unsetall fot clear all env pars
/bin/ls
can't execute
return code: 0
Bus error (core dumped)
У вас осталась последняя попытка сдачи работы.

**Comment by ubique** [comment]
Зачтено.

**Pull request closed without merging**
