### PR TITLE
Mikhail Terentev M3236

### PR DESCRIPTION
**Pull request by mikeTerentev**

### CODE REVIEW

**Comment by ubique** [comment]
Давайте умерим аппетиты Cmake:

$ cmake ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.13 or higher is required.  You are running version 3.12.1


-- Configuring incomplete, errors occurred!

**Comment by mikeTerentev** [comment]
> Давайте умерим аппетиты Cmake:
> 
> $ cmake ..
> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
> CMake 3.13 or higher is required. You are running version 3.12.1
> 
> -- Configuring incomplete, errors occurred!

fixed

**Comment by ubique** [comment]
$ make
Scanning dependencies of target OS_course
[ 50%] Building CXX object CMakeFiles/OS_course.dir/shell.cpp.o
/home/amnesia/git/ifmo/os-kidshell/shell.cpp: In function ‘std::vector<std::__cxx11::basic_string<char> > split_line(const string&)’:
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:28: error: ‘istream_iterator’ was not declared in this scope
     vector<string> results(istream_iterator<string>{iss},
                            ^~~~~~~~~~~~~~~~
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:28: note: ‘std::istream_iterator’ is defined in header ‘<iterator>’; did you forget to ‘#include <iterator>’?
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:7:1:
+#include <iterator>
 #include <string>
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:28:
     vector<string> results(istream_iterator<string>{iss},
                            ^~~~~~~~~~~~~~~~
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:51: error: expected primary-expression before ‘>’ token
     vector<string> results(istream_iterator<string>{iss},
                                                   ^
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:52: error: expected primary-expression before ‘{’ token
     vector<string> results(istream_iterator<string>{iss},
                                                    ^
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:39:51: error: expected primary-expression before ‘>’ token
                            istream_iterator<string>());
                                                   ^
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:39:53: error: expected primary-expression before ‘)’ token
                            istream_iterator<string>());
                                                     ^
/home/amnesia/git/ifmo/os-kidshell/shell.cpp: In function ‘void printErrorMessage(const string&, int)’:
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:53:32: error: ‘strerror’ was not declared in this scope
     cerr << message + " : " << strerror(type) << endl;
                                ^~~~~~~~
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:53:32: note: suggested alternative: ‘perror’
     cerr << message + " : " << strerror(type) << endl;
                                ^~~~~~~~
                                perror
/home/amnesia/git/ifmo/os-kidshell/shell.cpp: In function ‘void run(std::vector<std::__cxx11::basic_string<char> >, char**)’:
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:89:13: error: ‘waitpid’ was not declared in this scope
         if (waitpid(pid, &status, 0) != -1) {
             ^~~~~~~
/home/amnesia/git/ifmo/os-kidshell/shell.cpp:89:13: note: suggested alternative: ‘getpid’
         if (waitpid(pid, &status, 0) != -1) {
             ^~~~~~~
             getpid
make[2]: *** [CMakeFiles/OS_course.dir/build.make:63: CMakeFiles/OS_course.dir/shell.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/OS_course.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by mikeTerentev** [comment]
> $ make
> Scanning dependencies of target OS_course
> [ 50%] Building CXX object CMakeFiles/OS_course.dir/shell.cpp.o
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp: In function ‘std::vector<std::__cxx11::basic_string > split_line(const string&)’:
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:28: error: ‘istream_iterator’ was not declared in this scope
> vector results(istream_iterator{iss},
> ^~~~~~~~~~~~~~~~
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:28: note: ‘std::istream_iterator’ is defined in header ‘’; did you forget to ‘#include ’?
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:7:1:
> +#include 
> #include 
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:28:
> vector results(istream_iterator{iss},
> ^~~~~~~~~~~~~~~~
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:51: error: expected primary-expression before ‘>’ token
> vector results(istream_iterator{iss},
> ^
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:38:52: error: expected primary-expression before ‘{’ token
> vector results(istream_iterator{iss},
> ^
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:39:51: error: expected primary-expression before ‘>’ token
> istream_iterator());
> ^
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:39:53: error: expected primary-expression before ‘)’ token
> istream_iterator());
> ^
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp: In function ‘void printErrorMessage(const string&, int)’:
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:53:32: error: ‘strerror’ was not declared in this scope
> cerr << message + " : " << strerror(type) << endl;
> ^~~~~~~~
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:53:32: note: suggested alternative: ‘perror’
> cerr << message + " : " << strerror(type) << endl;
> ^~~~~~~~
> perror
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp: In function ‘void run(std::vector<std::__cxx11::basic_string >, char**)’:
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:89:13: error: ‘waitpid’ was not declared in this scope
> if (waitpid(pid, &status, 0) != -1) {
> ^~~~~~~
> /home/amnesia/git/ifmo/os-kidshell/shell.cpp:89:13: note: suggested alternative: ‘getpid’
> if (waitpid(pid, &status, 0) != -1) {
> ^~~~~~~
> getpid
> make[2]: *** [CMakeFiles/OS_course.dir/build.make:63: CMakeFiles/OS_course.dir/shell.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/OS_course.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2

fixed
p.s. ох уж этот мак

**Comment by ubique** [comment]
Зачтено.

**Pull request closed without merging**
